// @ts-check
import { defineConfig } from 'astro/config';
import vue from '@astrojs/vue';
import sitemap from '@astrojs/sitemap';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://redpulse.tech',
  integrations: [
    // The wiki (docs/REDESIGN.md, E). Starlight builds its routes from the file
    // paths under src/content/docs, so keeping everything in a `wiki/` folder is
    // what puts it on redpulse.tech/wiki — a subpath, not a subdomain, so the
    // SEO stays on the main domain.
    starlight({
      title: {
        pl: 'RedPulse Wiki',
        en: 'RedPulse Wiki',
      },
      description: 'Dokumentacja aplikacji RedPulse Innovations.',
      // No `locales` here on purpose: Starlight refuses to run alongside an
      // Astro `i18n` config, so the site-wide one below stays the single source
      // of truth. It already gives us Polish at the root and English under /en/.
      // Styled with the site's own tokens so the wiki reads as part of the
      // portal rather than as stock documentation.
      customCss: ['./src/styles/wiki.css'],
      social: [
        { icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/company/red-pulse-innovations/' },
        { icon: 'github', label: 'GitHub', href: 'https://github.com/DawidAdamski' },
      ],
      sidebar: [
        {
          label: 'AleDrogi Chat',
          // Since Starlight 0.39 an autogenerated group is a normal group whose
          // items carry the autogenerate config.
          items: [{ autogenerate: { directory: 'wiki/aledrogi-chat' } }],
        },
      ],
      // The marketing site owns the 404 page.
      disable404Route: true,
      credits: false,
    }),
    vue(),
    sitemap({ filter: (page) => !page.includes('/admin') }),
  ],
  i18n: {
    defaultLocale: 'pl',
    locales: ['pl', 'en'],
    routing: {
      prefixDefaultLocale: false
    }
  }
});
